### PR TITLE
Use gnu-tar on macOS

### LINKED ISSUE #69: swiftlint doesn't work after restoring from cache on macOS
https://github.com/Cyberbeni/install-swift-tool/runs/1335767035?check_suite_focus=true

### PR DESCRIPTION
**Pull request by Cyberbeni**

### CODE REVIEW

**Comment by Cyberbeni** [comment]
Resolves #69

File: src/environment_fixer.ts [hunk 1]
```diff
@@ -3,7 +3,23 @@ import * as fs from 'fs'
 import * as os from 'os'
 import { env } from 'process'
 
+import { exec } from './helpers'
+
 export class SwiftEnvironmentFixer {
+	static async fixTar(): Promise<void> {
+		await core.group(`Ensuring gnu-tar is used`, async () => {
```
Comment (Cyberbeni) [inline src/environment_fixer.ts]: - [x] only do this if caching is enabled
- [x] HOMEBREW_NO_AUTO_UPDATE=1

**Comment by Cyberbeni** [comment]
Seems like it's compatible with bsdtar caches: `/usr/local/opt/gnu-tar/libexec/gnubin/tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'`

**Comment by Cyberbeni** [comment]
- [x] Update readme
- [x] Wait a bit for official answer on the issue in actions/toolkit
- [x] Maybe also remove from path after run, similarly how it is added: https://github.com/actions/toolkit/blob/ff4308098f21f7e3dc05b50eb755043fadd8c3b1/packages/core/src/core.ts#L74
